## Import Libraries

In [1]:
from utils import ArmHandler
from time import sleep
import numpy as np
import cv2
from random import randint

SDK_VERSION: 1.13.8


In [2]:
arm = ArmHandler()

ROBOT_IP: 192.168.1.155, VERSION: v2.2.0, PROTOCOL: V1, DETAIL: 6,9,LI1006,DL1000,v2.2.0, TYPE1300: [0, 0]
change protocol identifier to 3


## Define Functions

In [3]:
def mouse_callback(event: int, x: int, y: int, flags, param):
    """
    Callback function for mouse events, Set the global variable point to the current pixel coordinates, (inverted Px,Py)
    """
    if event == cv2.EVENT_LBUTTONDOWN:
        global point
        point = (y, x)


def add_rows(matrix, row):
    if matrix.size == 0:
        return np.array(row).reshape(1, -1)
    else:
        return np.vstack((matrix, np.array(row)))

## Start Video Capture

In [4]:
cap = cv2.VideoCapture(0)
cap.set(3, 640)
cap.set(4, 480)
cv2.namedWindow("Video")
cv2.setMouseCallback("Video", mouse_callback)

## Save File

In [5]:
save_file = "calibration_data/points_new.txt"

## Collect Data Points

In [7]:
f = open(save_file, "a")
for i in range(25):
    arm.pickup_and_wait()
    bot_x, bot_y = (randint(215, 275), randint(0, 300))
    arm.place_block_on(bot_x, bot_y, z=27)

    point: tuple[int, int] | None = None


    while not point:
        ret, frame = cap.read()
        cv2.imshow("Video", frame)
        if cv2.waitKey(1) & 0xFF == ord('q'):
            break
    if not point:  # If user exits the loop, point maybe None
        break

    print(f"Robot: {(bot_x, bot_y)}, Pixel: {point}")
    f.write(f"{(bot_x, bot_y)},{point}\n")
f.close()

Robot: (231, 129), Pixel: (98, 313)
Robot: (240, 33), Pixel: (120, 161)
Robot: (221, 166), Pixel: (82, 370)
Robot: (251, 72), Pixel: (131, 223)
Robot: (275, 17), Pixel: (177, 135)
Robot: (258, 44), Pixel: (147, 180)
Robot: (230, 44), Pixel: (100, 178)
Robot: (266, 270), Pixel: (134, 520)
Robot: (255, 47), Pixel: (139, 184)
Robot: (228, 300), Pixel: (86, 569)
Robot: (256, 22), Pixel: (149, 146)
Robot: (268, 29), Pixel: (163, 155)
Robot: (274, 127), Pixel: (165, 309)
Robot: (218, 187), Pixel: (72, 396)
Robot: (236, 228), Pixel: (101, 465)
Robot: (252, 22), Pixel: (141, 142)
Robot: (258, 96), Pixel: (141, 263)
Robot: (255, 134), Pixel: (139, 317)
Robot: (271, 244), Pixel: (158, 494)
Robot: (266, 205), Pixel: (152, 433)
Robot: (249, 202), Pixel: (127, 426)
Robot: (234, 16), Pixel: (111, 137)
Robot: (272, 84), Pixel: (166, 241)
Robot: (265, 219), Pixel: (148, 454)
Robot: (262, 179), Pixel: (141, 390)


## Process Data, and find the transformation matrix

In [8]:
Rx = np.array([])
Ry = np.array([])
Px = np.array([])
Py = np.array([])

with open(save_file) as f:
    for line in set(f.readlines()):
        bot_coords, pixel_coords = eval(line)
        Rx = add_rows(Rx, [bot_coords[0]])
        Ry = add_rows(Ry, [bot_coords[1]])
        Px = add_rows(Px, [pixel_coords[0]])  # ...(Px,[pixel_coords[0],1]) - old using no rotation assumption
        Py = add_rows(Py, [pixel_coords[1]])  # ...(Py,[pixel_coords[1],1]) - old using no rotation assumption
print(Rx.size)
R = np.concatenate([Rx.T, Ry.T, np.ones(Rx.size).T.reshape(1, -1)], axis=0)
P = np.concatenate([Px.T, Py.T, np.ones(Px.size).T.reshape(1, -1)], axis=0)
W = R @ np.linalg.pinv(P)
print(W)

mx1, my1, c1, mx2, my2, c2 = map(lambda x: round(x, 16), (W[0, 0], W[0, 1], W[0, 2], W[1, 0], W[1, 1], W[1, 2]))

print(f"mx1,my1,cx1 = {mx1},{my1},{c1}")
print(f"mx2,my2,cx2 = {mx2},{my2},{c2}")

# old using no rotation assumption
# m1, c1 = np.linalg.pinv(Px) @ Rx
# m2, c2 = np.linalg.pinv(Py) @ Ry
# 
# m1, c1 = round(m1[0], 16), round(c1[0], 16)
# m2, c2 = round(m2[0], 16), round(c2[0], 16)
# print(f"m1,c1 = {m1},{c1}")
# print(f"m2,c2 = {m2},{c2}")

26
[[ 6.28597596e-01  2.67087726e-02  1.60824056e+02]
 [-2.67898933e-02  6.43853057e-01 -6.74281844e+01]
 [-9.10729825e-18 -1.30104261e-18  1.00000000e+00]]
mx1,my1,cx1 = 0.628597595853889,0.0267087725589912,160.82405585806336
mx2,my2,cx2 = -0.0267898933443885,0.6438530565199398,-67.42818435735794


In [6]:
# Hand Calculated (2 blocks):
# m1, c1 = 0.7251, 179.5495
# m2, c2 = 0.6383, -82.3553
# 10 blocks:
# m1, c1 = 0.71108,179.96984
# m2,c2 = 0.63734, -87.31099
# 39 blocks:
# m1,c1 = 0.56171, 197.02872
# m2,c2 = 0.64017,-85.75084
# 50 blocks:
# m1, c1 = 0.54665, 198.17924
# m2, c2 = 0.64072, -86.07211
# Reposition - 50 blocks
# m1, c1 = 0.6519, 150.83156
# m2,c2 = 0.64737, -84.42875
# Reposition - 50 blocks
# m1, c1 = 0.6456, 151.74737
# m2, c2 = 0.65968, -88.87191
# Same - 75 blocks
# m1, c1 = 0.6515, 150.83251
# m2, c2 = 0.65973, -88.76217
mx1,my1,c1 = 0.7163256447,-0.003082996,136.6934505941
mx2,my2,c2 = 0.0057453802,0.689476018,-86.7984923438

def pixel_to_world(px, py):
    return mx1 * px + my1 * py + c1, mx2 * px + my2 * py + c2  # m1 * px + c1, m2 * py + c2 - old using no rotation assumption

In [7]:
point = None
while True:
    if point is not None:
        rx, ry = pixel_to_world(point[0], point[1])
        print("Pixel: ", point)
        print(f"World: ({rx}, {ry})")
        if arm.pickup_block_from(rx, ry):
            arm.place_block_on()
        point = None

    ret, frame = cap.read()
    cv2.imshow("Video", frame)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

Pixel:  (209, 514)
World: (284.82085039239996, 268.79296537000005)
Pixel:  (150, 361)
World: (243.0293357431, 162.9641571842)
Pixel:  (170, 301)
World: (257.54082839710003, 121.71050370819998)
Pixel:  (226, 550)
World: (296.8873984963, 293.7117734814)


: 

In [9]:
arm.disconnect()
cap.release()
cv2.destroyAllWindows()

: 